from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle,
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

from docx import Document
from docx.shared import Inches


styles = getSampleStyleSheet()


def build_pdf_report(report_data: dict):

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=30,
    )

    elements = []

    metadata = report_data["report_metadata"]

    title = metadata["report_title"]

    project = metadata["project_name"]

    company = metadata.get(
        "company_name",
        "Engineering Company"
    )

    generated_at = metadata["generated_at"]


    elements.append(
        Paragraph(
            f"<b>{company}</b>",
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            f"<font size=22><b>{title}</b></font>",
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            f"<b>Project:</b> {project}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Generated:</b> {generated_at}",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 40)
    )

    elements.append(
        Paragraph(
            "<b>Executive Summary</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    elements.append(
        Paragraph(
            report_data.get(
                "executive_summary",
                ""
            ),
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 30)
    )


    elements.append(
        Paragraph(
            "<b>Engineering KPIs</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    kpi_data = [["KPI", "Value"]]

    for item in report_data["kpis"]:

        kpi_data.append([
            item["label"],
            str(item["value"])
        ])

    kpi_table = Table(
        kpi_data,
        colWidths=[220, 220]
    )

    kpi_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
        ])
    )

    elements.append(
        kpi_table
    )

    elements.append(
        Spacer(1, 30)
    )


    elements.append(
        Paragraph(
            "<b>Compliance</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    compliance = report_data["compliance"]

    elements.append(
        Paragraph(
            f"<b>Status:</b> {compliance['status']}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Compliance Score:</b> {compliance['score']} %",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 30)
    )


    elements.append(
        Paragraph(
            "<b>Recommendations</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    for recommendation in report_data["recommendations"]:

        elements.append(
            Paragraph(
                f"• {recommendation['recommendation']}",
                styles["BodyText"]
            )
        )

        elements.append(
            Spacer(1, 6)
        )


    elements.append(
        Spacer(1, 40)
    )

    elements.append(
        Paragraph(
            "Generated by Electrical AI Engineering Platform",
            styles["Italic"]
        )
    )

    document.build(
        elements
    )

    buffer.seek(0)

    return buffer


def build_docx_report(
    report_data: dict
):

    document = Document()

    metadata = report_data[
        "report_metadata"
    ]

    document.add_heading(
        metadata["report_title"],
        level=1
    )

    document.add_paragraph(
        f"Project: {metadata['project_name']}"
    )

    document.add_paragraph(
        f"Generated: {metadata['generated_at']}"
    )

    document.add_heading(
        "Executive Summary",
        level=2
    )

    document.add_paragraph(
        report_data.get(
            "executive_summary",
            ""
        )
    )

    document.add_heading(
        "Engineering KPIs",
        level=2
    )

    table = document.add_table(
        rows=1,
        cols=2
    )

    hdr_cells = table.rows[0].cells

    hdr_cells[0].text = "KPI"

    hdr_cells[1].text = "Value"

    for item in report_data["kpis"]:

        row_cells = table.add_row().cells

        row_cells[0].text = item["label"]

        row_cells[1].text = str(
            item["value"]
        )

    document.add_heading(
        "Compliance",
        level=2
    )

    compliance = report_data["compliance"]

    document.add_paragraph(
        f"Status: {compliance['status']}"
    )

    document.add_paragraph(
        f"Score: {compliance['score']} %"
    )

    document.add_heading(
        "Recommendations",
        level=2
    )

    for recommendation in report_data[
        "recommendations"
    ]:

        document.add_paragraph(
            recommendation["recommendation"],
            style="List Bullet"
        )

    output = BytesIO()

    document.save(output)

    output.seek(0)

    return output
